version: "3"

env:
    ENV: '{{.ENV | default "minikube" }}'

vars:
  GENERAL_NAME: wa-general
  GENERAL_CHART: ./general
  PLAYBACK_NAME: wa-playback
  PLAYBACK_CHART: ./playback
  MOCKILS_NAME: wa-mocked-ils
  MOCKILS_CHART: ./mocked-ils
  GRAPH_NAME: wa-graph
  GRAPH_CHART: ./graph
  INGEST_NAME: wa-ingest
  INGEST_CHART: ./ingest

tasks:
  default:
    desc: List the tasks
    cmds:
      - task -l

  setup:minikube:
    desc: Setup the relevant stuff for local minikube setup
    cmds:
      - task: install:mock:example-data
      - minikube addons enable ingress

  install:
    aliases: [deploy]
    desc: Install/deploy the webarchive setup
    deps:
      - task: install:general
      - task: install:graph
      - task: install:playback
      - task: install:mockils
      - task: install:ingest

  install:general:
    desc: Install/deploy the  general things
    cmds:
      - helm install -f {{.GENERAL_CHART}}/values-{{.ENV}}.yaml {{.GENERAL_NAME}} {{.GENERAL_CHART}}

  install:playback:
    desc: Install/deploy the playback setup
    cmds:
      - helm install -f {{.PLAYBACK_CHART}}/values-{{.ENV}}.yaml {{.PLAYBACK_NAME}} {{.PLAYBACK_CHART}}

  install:mockils:
    desc: Install/deploy the mockils setup
    cmds:
      - helm install {{.MOCKILS_NAME}} {{.MOCKILS_CHART}}

  install:graph:
    desc: Install/deploy the website knowledge graph setup
    cmds:
      - helm install {{.GRAPH_NAME}} {{.GRAPH_CHART}}

  install:ingest:
    desc: Install/deploy the ingest setup
    cmds:
      - helm install {{.INGEST_NAME}} {{.INGEST_CHART}}

  upgrade:
    desc:  Upgrade the deployed webarchive setup
    deps:
      - task: upgrade:general
      - task: upgrade:graph
      - task: upgrade:playback
      - task: upgrade:mockils
      - task: upgrade:ingest

  upgrade:general:
    desc: Upgrade the general setup
    cmds:
      - helm upgrade -f {{.GENERAL_CHART}}/values-{{.ENV}}.yaml {{.GENERAL_NAME}} {{.GENERAL_CHART}}

  upgrade:playback:
    desc: Upgrade the playback setup
    cmds:
      - helm upgrade -f {{.PLAYBACK_CHART}}/values-{{.ENV}}.yaml {{.PLAYBACK_NAME}} {{.PLAYBACK_CHART}}

  upgrade:mockils:
    desc: Upgrade the mockils setup
    cmds:
      - helm upgrade {{.MOCKILS_NAME}} {{.MOCKILS_CHART}}

  upgrade:graph:
    desc: Upgrade the website knowledge graph setup
    cmds:
      - helm upgrade {{.GRAPH_NAME}} {{.GRAPH_CHART}}

  upgrade:ingest:
    desc: Upgrade the ingest setup
    cmds:
      - helm upgrade {{.INGEST_NAME}} {{.INGEST_CHART}}

  uninstall:
    desc:  Uninstall the deployed webarchive setup
    deps:
      - task: uninstall:general
      - task: uninstall:graph
      - task: uninstall:playback
      - task: uninstall:mockils
      - task: uninstall:ingest

  uninstall:general:
    desc: Uninstall the general stuff
    cmds:
      - helm uninstall {{.GENERAL_NAME}}

  uninstall:playback:
    desc: Uninstall the playback setup
    cmds:
      - helm uninstall {{.PLAYBACK_NAME}}

  uninstall:mockils:
    desc: Uninstall the mockils setup
    cmds:
      - helm uninstall {{.MOCKILS_NAME}}

  uninstall:graph:
    desc: Uninstall the website knowledge graph setup
    cmds:
      - helm uninstall {{.GRAPH_NAME}}

  uninstall:ingest:
    desc: Uninstall the ingest setup
    cmds:
      - helm uninstall {{.INGEST_NAME}}

  check:
    aliases: [lint]
    desc: Verify the syntax
    cmds:
      - task: check:general
      - task: check:graph
      - task: check:playback
      - task: check:mockils
      - task: check:ingest

  check:general:
    desc: Verify the syntax of general things
    cmds:
      - helm lint {{.GENERAL_CHART}}
      - helm install --debug --dry-run {{.GENERAL_NAME}} {{.GENERAL_CHART}}

  check:playback:
    desc: Verify the syntax of playback
    cmds:
      - helm lint {{.PLAYBACK_CHART}}
      - helm install --debug --dry-run {{.PLAYBACK_NAME}} {{.PLAYBACK_CHART}}

  check:graph:
    desc: Verify the syntax of graph
    cmds:
      - helm lint {{.GRAPH_CHART}}
      - helm install --debug --dry-run {{.GRAPH_NAME}} {{.GRAPH_CHART}}

  check:mockils:
    desc: Verify the syntax of mockils
    cmds:
      - helm lint {{.MOCKILS_CHART}}
      - helm install --debug --dry-run {{.MOCKILS_NAME}} {{.MOCKILS_CHART}}

  check:ingest:
    desc: Verify the syntax of ingest
    cmds:
      - helm lint {{.INGEST_CHART}}
      - helm install --debug --dry-run {{.INGEST_NAME}} {{.INGEST_CHART}}

  debug:
    desc: Collect some information helpful for debugging
    summary: |
      Also check out https://helm.sh/docs/chart_template_guide/debugging/
    cmds:
      - helm get manifest {{.PLAYBACK_NAME}}

  install:mock:example-data:
    desc: Copy the example data to a minikube
    cmds:
      - ssh-keygen -R $(minikube ip)
      - scp -r -i $(minikube ssh-key) examples/hostdata docker@$(minikube ip):/home/docker/
