version: "3"

dotenv: ['{{.ENV}}.env', 'custom.env', 'default.env']

tasks:
  default:
    desc: List the tasks
    cmds:
      - |
        echo "ENV: {{.ENV}}"
        echo "NAMESPACE: {{.NAMESPACE}}"
        task -l

  install:
    aliases: [deploy]
    desc: Install/deploy the webarchive setup
    cmds:
      - helm upgrade --namespace {{.NAMESPACE}} --install -f values-{{.ENV}}.yaml webarchive .

  uninstall:
    desc:  Uninstall the deployed webarchive setup
    cmds:
      - helm uninstall --namespace {{.NAMESPACE}} webarchive

  check:
    aliases: [lint]
    desc: Verify the syntax
    cmds:
      - helm lint .

  dry-run:
    desc: Do a dry-run
    cmds:
      - helm install --dry-run=client -f values-{{.ENV}}.yaml webarchive .


  setup:minikube:
    desc: Setup the relevant stuff for local minikube setup
    cmds:
      - task: install:mock:example-data
      - minikube addons enable ingress

  install:mock:example-data:
    desc: Copy the example data to a minikube
    cmds:
      - ssh-keygen -R $(minikube ip)
      - scp -r -i $(minikube ssh-key) examples/hostdata docker@$(minikube ip):/home/docker/

  install:copy-example-dags:
    desc: Copy the example dags to the deployment
    cmd: |
      for file in examples/airflow/dags/*; do
        kubectl cp $file {{.NAMESPACE}}/webarchive-worker-0:/opt/airflow/dags -c worker;
      done;

  debug:
    desc: Collect some information helpful for debugging
    summary: |
      Also check out https://helm.sh/docs/chart_template_guide/debugging/
    cmds:
      - helm get manifest {{.PLAYBACK_NAME}}


  helm:dependencies:
    desc: Install and update Helm chart dependencies
    cmds:
      - helm dependency build

  helm:dependencies:update:
    desc: Install and update Helm chart dependencies
    cmds:
      - helm dependency update

  helm:setup:repo:
    desc: Add the Apache Airflow Helm repository to the local Helm configuration
    cmds:
      - helm repo add apache-airflow https://airflow.apache.org
      - helm repo add zazuko https://charts.zazuko.com


  port-forward:airflow:
    desc: Forward the api server port to 8080 in 0.0.0.0
    interactive: true
    cmds:
      - kubectl port-forward --address=0.0.0.0 services/webarchive-api-server 8080:8080 --namespace {{.NAMESPACE}}

  port-forward:s3:api:
    desc: Forward the api server port to 8080 in 0.0.0.0
    interactive: true
    cmds:
      - kubectl port-forward --address=0.0.0.0 services/webarchive-versitygw 7070:7070 --namespace {{.NAMESPACE}}

  port-forward:s3:admin:
    desc: Forward the api server port to 8080 in 0.0.0.0
    interactive: true
    cmds:
      - kubectl port-forward --address=0.0.0.0 services/webarchive-versitygw 7071:7071 --namespace {{.NAMESPACE}}

  port-forward:s3:webui:
    desc: Forward the api server port to 8080 in 0.0.0.0
    interactive: true
    cmds:
      - kubectl port-forward --address=0.0.0.0 services/webarchive-versitygw 8082:8080 --namespace {{.NAMESPACE}}

  port-forward:fuseki:
    desc: Forward the api server port to 8080 in 0.0.0.0
    interactive: true
    cmds:
      - kubectl port-forward --address=0.0.0.0 services/webarchive-fuseki 3030:3030 --namespace {{.NAMESPACE}}
