global:
  imagePullPolicy: IfNotPresent

airflow:
  dags:
    persistence:
      enabled: true
      existingClaim: dags-pvc
    gitSync:
      enabled: false
  # issue: https://github.com/apache/airflow/issues/58417
  config:
    # webserver:
    #   base_url: "http://192.168.39.238/airflow"
    core:
      hostname_callable: airflow.utils.net.get_host_ip_address
  ingress:
    enabled: true
    apiServer:
      ingressClassName: nginx
      path: /airflow(/|$)(.*)

versitygw:
  auth:
    accessKey: myaccesskey
    secretKey: mysecretkey
  # serviceAccount:
  #   create: true
  #   name: airflow-versitygw-s3
  admin:
    enabled: true
  webui:
    enabled: true
    apiGateways:
      - http://localhost:7070
    adminGateways:
      - http://localhost:7071
  gateway:
    region: eu-central-1
    backend:
      type: posix
  # ingress:
  #   enabled: true
  #   annotations:
  #     nginx.ingress.kubernetes.io/use-regex: "true"
  #     nginx.ingress.kubernetes.io/rewrite-target: /$2
  #   hosts:
  #     - paths:
  #       - path: /s3webui(/|$)(.*)
  #         pathType: ImplementationSpecific
  #         servicePort: webui
  #       - path: /s3(/|$)(.*)
  #         pathType: ImplementationSpecific
  #         servicePort: s3-api
fuseki:
  volumeMounts:
    - mountPath: /fuseki/configuration/config.ttl
      name: config-ttl
      subPath: "config.ttl"
      readOnly: true
  volumes:
    - name: config-ttl
      configMap:
        name: fuseki-configmap
        items:
          - key: "config.ttl"
            path: "config.ttl"
  # ingress:
  #   enabled: true
  #   annotations:
  #     nginx.ingress.kubernetes.io/use-regex: "true"
  #     nginx.ingress.kubernetes.io/rewrite-target: /$2
  #   hosts:
  #     - paths:
  #       - path: /fuseki(/|$)(.*)
  #         pathType: ImplementationSpecific
