# null overrides in parent values.yaml ignored for always-enabled subcharts #32132
# https://github.com/helm/helm/issues/32132#issuecomment-4497479333
# the following 6 lines are required
airflow:
  enabled: true
  apiSecretKey: "examplesecrettobechanged"
versitygw:
  enabled: true
fuseki:
  enabled: true

pwidresolver:
  pwidResolverBasePath: "/pwidresolver"
  pwidResolverLoglevel: "DEBUG"