# null overrides in parent values.yaml ignored for always-enabled subcharts #32132
# https://github.com/helm/helm/issues/32132#issuecomment-4497479333
airflow:
  enabled: true
  uid: null
  gid: null
  apiServer:
    resources:
      limits:
        cpu: 400m
        memory: 512Mi
      requests:
        cpu: 400m
        memory: 512Mi
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 60
    # readinessProbe:
    #   initialDelaySeconds: 60
    #   periodSeconds: 30
    #   timeoutSeconds: 10
  scheduler:
    resources:
      limits:
        cpu: 360m
        memory: 400Mi
      requests:
        cpu: 360m
        memory: 400Mi
    startupProbe:
      initialDelaySeconds: 30
      periodSeconds: 60
      timeoutSeconds: 40
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 40
      periodSeconds: 60
    logGroomerSidecar:
      resources:
        limits:
          cpu: 5m
          memory: 150Mi
        requests:
          cpu: 5m
          memory: 150Mi
  dagProcessor:
    resources:
      limits:
        cpu: 360m
        memory: 512Mi
      requests:
        cpu: 360m
        memory: 512Mi
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 40
      periodSeconds: 60
    logGroomerSidecar:
      resources:
        limits:
          cpu: 5m
          memory: 150Mi
        requests:
          cpu: 5m
          memory: 150Mi
  redis:
    uid: null
    resources:
      limits:
        cpu: 5m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 64Mi
  statsd:
    uid: null
    resources:
      limits:
        cpu: 5m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 64Mi
  postgresql:
    primary:
      podSecurityContext:
        fsGroup: null
      containerSecurityContext:
        runAsUser: null
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 256Mi
        # requests: null
  triggerer:
    persistence:
      size: 10Gi
    resources:
      limits:
        cpu: 300m
        memory: 600Mi
      requests:
        cpu: 300m
        memory: 600Mi
        # cpu: null
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 60
      periodSeconds: 120
    logGroomerSidecar:
      resources:
        limits:
          cpu: 5m
          memory: 150Mi
        requests:
          cpu: 5m
          memory: 150Mi
  workers:
    persistence:
      size: 10Gi
    celery:
      resources:
        limits:
          cpu: 1250m
          memory: 4Gi
        requests:
          cpu: 1000m
          memory: 4Gi
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 60
        timeoutSeconds: 40
      logGroomerSidecar:
        resources:
          limits:
            cpu: 5m
            memory: 150Mi
          requests:
            cpu: 5m
            memory: 150Mi
    kubernetes:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 1000m
          memory: 1Gi
      # Add this to set default resources for KubernetesPodOperator tasks:
      podTemplate:
        spec:
          containers:
            - name: base
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
                requests:
                  cpu: 500m
                  memory: 1Gi
  migrateDatabaseJob:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 256Mi
  createUserJob:
    resources:
      limits:
        cpu: 125m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 256Mi

versitygw:
  enabled: true
  podSecurityContext:
    fsGroup: null
  securityContext:
    runAsUser: null
    runAsGroup: null
  resources:
    limits:
      cpu: 250m
      memory: 200Mi
    requests:
      cpu: 125m
      memory: 200Mi

fuseki:
  enabled: true
  podSecurityContext:
    fsGroup: null
    runAsUser: null
    runAsGroup: null
  securityContext:
    runAsUser: null
    seLinuxOptions: null
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 4Gi
  readinessProbe:
    timeoutSeconds: 5
    periodSeconds: 30

pwidresolver:
  pwidResolverLoglevel: "DEBUG"
  resources:
    limits:
      cpu: 10m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 256Mi

playback:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

dashboard:
  resources:
    limits:
      cpu: 5m
      memory: 32Mi
    requests:
      cpu: 5m
      memory: 32Mi

outbackcdx:
  resources:
    limits:
      cpu: 1500m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 1Gi
