apiVersion: v1
kind: ConfigMap
metadata:
  name: wapmh-configmap
data:
  SPARQL_ENDPOINT: {{ .Values.sparqlEndpoint | quote }}
  QUERY_PATH: {{ .Values.queryDirectory | quote }}
  ADMIN_EMAILS: '["n.arndt@dnb.de"]'
  LIMIT: "1"