kind: Deployment
apiVersion: apps/v1
metadata:
  name: outbackcdx-app
  labels:
    app: outbackcdx
spec:
  selector:
    matchLabels:
      app: outbackcdx
  template:
    metadata:
      labels:
        app: outbackcdx
    spec:
      containers:
        - name: outbackcdx-app
          image: 'docker.io/nlagovau/outbackcdx:1.1.1'
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          command: ["java", "-jar", "outbackcdx.jar", "-v", "-d", "/data", "-p", "8080", "-b", "0.0.0.0", "--context-path", "/outbackcdx"]
          volumeMounts:
            - mountPath: /data
              name: cdx-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: cdx-data
          persistentVolumeClaim:
            claimName: {{ .Values.pvcName | quote }}