kind: Deployment
apiVersion: apps/v1
metadata:
  name: wacalog-app
  labels:
    app: wacalog
spec:
  selector:
    matchLabels:
      app: wacalog
  template:
    metadata:
      labels:
        app: wacalog
    spec:
      initContainers:
        - name: wacalog-template-clone
          image: 'registry.k8s.io/git-sync/git-sync:v4.5.0'
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          args:
            - "--repo=https://github.com/deutsche-nationalbibliothek/wacalog"
            - "--root=/data"
            - "--link=latest"
            - "--depth=1"
            - "--one-time"
          volumeMounts:
            - mountPath: "/data"
              name: wacalog-templates
          resources:
            {{- toYaml .Values.initClone.resources | nindent 12 }}
      containers:
        - name: wacalog-serve
          # image: 'ghcr.io/aksw/kefar:main'
          image: 'ghcr.io/aksw/kefar:main@sha256:572a324cdf4185d9cb2b2a360f0f6baefb1afd9df459be019ce189f2de3edf47'
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          workingDir: /data/latest
          volumeMounts:
            - mountPath: "/data"
              name: wacalog-templates
            - mountPath: "/data/latest/mkdocs.yml"
              name: wacalog-config
              subPath: "mkdocs.yml"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: wacalog-templates
          emptyDir:
            sizeLimit: 1Gi
        - name: wacalog-config
          configMap:
            name: wacalog-configmap
            items:
              - key: "mkdocs.yml"
                path: "mkdocs.yml"
