resources: {}

initClone:
  resources: {}

initBuild:
  resources: {}

playbackBase: "http://your-host.example/wayback/warcs/"
mkrdf:
  sparqlEndpoint: "http://webarchive-fuseki:3030/ds/query"
  baseIri: "https://webarchiv.dnb.de/"
  homeIri: "https://webarchiv.dnb.de/"