{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: airflow
spec:
  to:
    kind: Service
    name: webarchive-api-server
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fuseki
spec:
  to:
    kind: Service
    name: webarchive-fuseki
  port:
    targetPort: 3030
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fuseki-apps-route
  # See also: https://docs.redhat.com/en/documentation/openshift_container_platform/4.13/html/networking/configuring-routes#nw-path-based-routes_route-configuration
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
spec:
  host: {{ .Values.global.routerHost | quote }}
  path: /fuseki/
  to:
    kind: Service
    name: webarchive-fuseki
  port:
    targetPort: 3030
{{- end }}