{{- if .Values.vpa.enabled }}
{{- if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-dashboard-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dashboard-app
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-outbackcdx-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: outbackcdx-app
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-pwidresolver-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pwidresolver-app
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-pywb-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pywb-app
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-api-server-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webarchive-api-server
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-dag-processor-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webarchive-dag-processor
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-scheduler-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webarchive-scheduler
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-statsd-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webarchive-statsd
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-versitygw-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webarchive-versitygw
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-fuseki-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: webarchive-fuseki
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-postgresql-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: webarchive-postgresql
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-redis-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: webarchive-redis
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-triggerer-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: webarchive-triggerer
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: webarchive-worker-vpa
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources:
          - cpu
        controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: webarchive-worker
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
{{- end }}
{{- end }}
