kind: Deployment
apiVersion: apps/v1
metadata:
  name: pywb-app
  labels:
    app: pywb
spec:
  selector:
    matchLabels:
      app: pywb
  template:
    metadata:
      labels:
        app: pywb
    spec:
      containers:
        - name: pywb-app
          image: 'docker.io/webrecorder/pywb:2.9.1'
          # image: 'ghcr.io/deutsche-nationalbibliothek/pywb:integration-preImage-uwsgiMount-entrypoint'
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          command: ["uwsgi"]
          # args: ["-c", "while [ true ]; do echo 1 & sleep infinity; done;"]
          args: ["/uwsgi/uwsgi.ini"]
          env:
            - name: UWSGI_MOUNT
              value: "{{ .Values.playbackBasePath }}=/pywb/pywb/apps/wayback.py"
            - name: AWS_ENDPOINT_URL_S3
              value: {{ .Values.s3Endpoint | quote }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.s3DefaultRegion | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3SecretKeyName | quote }}
                  key: rootAccessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3SecretKeyName | quote }}
                  key: rootSecretAccessKey
          volumeMounts:
            - mountPath: {{ .Values.warcDirectory | quote }}
              name: warcs
            - mountPath: "/webarchive/config.yaml"
              subPath: "config.yaml"
              name: pywb-config
              readOnly: true
      volumes:
        - name: warcs
          persistentVolumeClaim:
            claimName: warcs-pvc
        - name: pywb-config
          configMap:
            name: pywb-configmap
            items:
              - key: "config.yaml"
                path: "config.yaml"
